### ISSUE TITLE
Optimize image sizes

### ISSUE THREAD

**Issue by siraben** [squ1rrel-ctf/squ1rrel.dev#27]
The images are very nice but slow down page loads significantly. Suggest using progressive JPEG maybe? Cloudflare also has image resizing.

**Comment by aadibajpai** [comment]
> The images are very nice but slow down page loads significantly. Suggest using progressive JPEG maybe? Cloudflare also has image resizing.

cloudflare image stuff is $5/month prob not worth. If we can convert to webp or something that would be hype I think

**Comment by aadibajpai** [comment]
closed by #32
